"""users-films-association-planned

Revision ID: a7ec8da83b5b
Revises: c5c28095e577
Create Date: 2025-01-29 20:55:05.619481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a7ec8da83b5b'
down_revision: Union[str, None] = 'c5c28095e577'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_film_association', sa.Column('status', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_film_association', 'status')
    # ### end Alembic commands ###
