"""users-films-association

Revision ID: c5c28095e577
Revises: 3beb90e20843
Create Date: 2025-01-29 20:34:31.510322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c5c28095e577'
down_revision: Union[str, None] = '3beb90e20843'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_film_association',
    sa.Column('user_uid', sa.UUID(), nullable=False),
    sa.Column('film_uid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['film_uid'], ['films.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_uid', 'film_uid')
    )
    op.add_column('films', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('films', sa.Column('year', sa.Integer(), nullable=True))
    op.add_column('films', sa.Column('poster', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_constraint('films_userUid_fkey', 'films', type_='foreignkey')
    op.drop_column('films', 'updated_at')
    op.drop_column('films', 'created_at')
    op.drop_column('films', 'userUid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('films', sa.Column('userUid', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('films', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('films', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_foreign_key('films_userUid_fkey', 'films', 'users', ['userUid'], ['uid'])
    op.drop_column('films', 'poster')
    op.drop_column('films', 'year')
    op.drop_column('films', 'title')
    op.drop_table('user_film_association')
    # ### end Alembic commands ###
